version: '3.8'

services:
  web:
    image: chat.app
    build:
      context: .
      dockerfile: SimpleChat/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy  
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"  
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"
      DefaultConnection: "Host=postgres;Port=5432;Database=chatappdb;Username=postgres;Password=mysecretpassword"

  postgres:
    image: postgres:latest
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "chatappdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: chatappdb
    ports:
      - "5432:5432"
